version: "3.9"
services:
    # lookdiscoverer
    lookdiscoverer:
        build:
            context: ./
            dockerfile: django.Dockerfile
        restart: unless-stopped
        volumes:
            - .:/usr/src/app:delegated
        ports:
            - "8000:8000"
        working_dir: /usr/src/app/lookdiscoverer
        environment:
            - PYTHONBUFFERED=1
            - DJANGO_SECRET_KEY=django
            - DB_NAME=locald
            - DB_HOST=mongodb://localhost:27017/
            - DJANGO_SUPERUSER_USERNAME=locald
            - DJANGO_SUPERUSER_PASSWORD=locald
            - DJANGO_SUPERUSER_EMAIL=locald@locald.fr
