# Generated by Django 3.2.5 on 2021-07-12 21:56

from django.db import migrations, models
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Look',
            fields=[
                ('look_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('look_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hype_count', models.IntegerField(blank=True, default=0)),
                ('hashtags', djongo.models.fields.JSONField(blank=True, null=True)),
                ('image_md5', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
